cuda: fix HIP compilation
While compiling current HEAD with HIP backend, the following compiler
error occurred:

	/build/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:3239:28: error: no matching function for call to 'hipStreamWaitEvent'
	 3239 |                 CUDA_CHECK(cudaStreamWaitEvent(stream, concurrent_event->fork_event));
	      |                            ^~~~~~~~~~~~~~~~~~~
	/build/llama.cpp/ggml/src/ggml-hip/../ggml-cuda/vendors/hip.h:112:29: note: expanded from macro 'cudaStreamWaitEvent'
	  112 | #define cudaStreamWaitEvent hipStreamWaitEvent
	      |                             ^~~~~~~~~~~~~~~~~~
	/build/llama.cpp/ggml/src/ggml-hip/../ggml-cuda/common.cuh:159:40: note: expanded from macro 'CUDA_CHECK'
	  159 | #define CUDA_CHECK(err) CUDA_CHECK_GEN(err, cudaSuccess, cudaGetErrorString)
	      |                                        ^~~
	/build/llama.cpp/ggml/src/ggml-hip/../ggml-cuda/common.cuh:153:22: note: expanded from macro 'CUDA_CHECK_GEN'
	  153 |         auto err_ = (err);                                                          \
	      |                      ^~~
	/usr/include/hip/hip_runtime_api.h:2211:12: note: candidate function not viable: requires 3 arguments, but 2 were provided
	 2211 | hipError_t hipStreamWaitEvent(hipStream_t stream, hipEvent_t event, unsigned int flags);

Dix this issue by passing the appropriate number of arguments.

Fixes: c7af376c2 ("CUDA: add stream-based concurrency (#16991)")
Signed-off-by: Jo-Philipp Wich <jo@mein.io>